name: Notify Discord

on:
  push:
    branches:
      - iranmp:multitheftauto/iran-mp  # agar branch digei dari, avaz kon

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }} # bayad set koni
          status: ${{ job.status }}
        if: always()
